"""add notifications and failed jobs 2

Revision ID: 208cb1708959
Revises: e2d8f469e557
Create Date: 2026-08-26 20:37:46.957429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208cb1708959'
down_revision: Union[str, None] = 'e2d8f469e557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failed_jobs', sa.Column('attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('failed_jobs', 'attempts')
    # ### end Alembic commands ###
