"""add ai interactions

Revision ID: 2a8e6fa9e4d3
Revises: e0528e149385
Create Date: 2026-09-03 03:29:45.515169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a8e6fa9e4d3'
down_revision: Union[str, None] = 'e0528e149385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('refused', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('product_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('variant_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interactions_correlation_id'), 'ai_interactions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ai_interactions_intent'), 'ai_interactions', ['intent'], unique=False)
    op.create_index(op.f('ix_ai_interactions_status'), 'ai_interactions', ['status'], unique=False)
    op.create_index(
        op.f("ix_ai_interactions_created_at"),
        "ai_interactions",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_interactions_status'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_intent'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_correlation_id'), table_name='ai_interactions')

    op.drop_index(
        op.f("ix_ai_interactions_created_at"),
        table_name="ai_interactions",
    )
    op.drop_table('ai_interactions')
    # ### end Alembic commands ###
