"""add user to ai interactions

Revision ID: 426a0db6a8d1
Revises: 7f83b961116a
Create Date: 2026-09-03 07:43:01.060637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426a0db6a8d1'
down_revision: Union[str, None] = '7f83b961116a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_interactions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_ai_interactions_user_id'), 'ai_interactions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ai_interactions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_interactions', type_='foreignkey')
    op.drop_index(op.f('ix_ai_interactions_user_id'), table_name='ai_interactions')
    op.drop_column('ai_interactions', 'user_id')
    # ### end Alembic commands ###
