"""add content chunks

Revision ID: 4edd105f16c9
Revises: f96b820b6db3
Create Date: 2026-08-19 19:35:52.480806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4edd105f16c9'
down_revision: Union[str, None] = 'f96b820b6db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'chunk_index', name='uq_content_chunks_product_chunk_index')
    )
    op.create_index(op.f('ix_content_chunks_product_id'), 'content_chunks', ['product_id'], unique=False)
    op.create_index(op.f('ix_content_chunks_text_hash'), 'content_chunks', ['text_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_chunks_text_hash'), table_name='content_chunks')
    op.drop_index(op.f('ix_content_chunks_product_id'), table_name='content_chunks')
    op.drop_table('content_chunks')
    # ### end Alembic commands ###
