"""add generated content

Revision ID: 7f83b961116a
Revises: 2a8e6fa9e4d3
Create Date: 2026-09-03 06:38:15.616704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f83b961116a'
down_revision: Union[str, None] = '2a8e6fa9e4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('description', 'seo', 'faq', name='generated_content_type'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_content_product_id'), 'generated_content', ['product_id'], unique=False)
    op.create_index(op.f('ix_generated_content_type'), 'generated_content', ['type'], unique=False)
    op.drop_index('ix_ai_interactions_created_at', table_name='ai_interactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ai_interactions_created_at', 'ai_interactions', ['created_at'], unique=False)
    op.drop_index(op.f('ix_generated_content_type'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_product_id'), table_name='generated_content')
    op.drop_table('generated_content')
    # ### end Alembic commands ###
