"""add analytics tables and product published at

Revision ID: 90a3f81be981
Revises: 208cb1708959
Create Date: 2026-08-27 15:46:56.238988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a3f81be981'
down_revision: Union[str, None] = '208cb1708959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stockouts', sa.Integer(), nullable=False),
    sa.Column('products_published', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('analytics_product',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.add_column('products', sa.Column('published_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'published_at')
    op.drop_table('analytics_product')
    op.drop_table('analytics_daily')
    # ### end Alembic commands ###
