"""add content chunk vector metadata

Revision ID: e0528e149385
Revises: 5a65f68d9814
Create Date: 2026-09-01 01:38:20.417850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0528e149385'
down_revision: Union[str, None] = '5a65f68d9814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_chunks', sa.Column('variant_id', sa.UUID(), nullable=True))
    op.add_column('content_chunks', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('content_chunks', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('content_chunks', sa.Column('status', sa.String(length=32), nullable=True))
    op.add_column('content_chunks', sa.Column('available', sa.Boolean(), nullable=True))
    op.add_column('content_chunks', sa.Column('in_stock', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_content_chunks_available'), 'content_chunks', ['available'], unique=False)
    op.create_index(op.f('ix_content_chunks_category_id'), 'content_chunks', ['category_id'], unique=False)
    op.create_index(op.f('ix_content_chunks_in_stock'), 'content_chunks', ['in_stock'], unique=False)
    op.create_index(op.f('ix_content_chunks_status'), 'content_chunks', ['status'], unique=False)
    op.create_index(op.f('ix_content_chunks_variant_id'), 'content_chunks', ['variant_id'], unique=False)
    op.create_foreign_key(None, 'content_chunks', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'content_chunks', 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_chunks', type_='foreignkey')
    op.drop_constraint(None, 'content_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_content_chunks_variant_id'), table_name='content_chunks')
    op.drop_index(op.f('ix_content_chunks_status'), table_name='content_chunks')
    op.drop_index(op.f('ix_content_chunks_in_stock'), table_name='content_chunks')
    op.drop_index(op.f('ix_content_chunks_category_id'), table_name='content_chunks')
    op.drop_index(op.f('ix_content_chunks_available'), table_name='content_chunks')
    op.drop_column('content_chunks', 'in_stock')
    op.drop_column('content_chunks', 'available')
    op.drop_column('content_chunks', 'status')
    op.drop_column('content_chunks', 'price')
    op.drop_column('content_chunks', 'category_id')
    op.drop_column('content_chunks', 'variant_id')
    # ### end Alembic commands ###
