"""enforce unique category names

Revision ID: f96b820b6db3
Revises: 6225739687fa
Create Date: 2026-08-19 14:33:44.345852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96b820b6db3'
down_revision: Union[str, None] = '6225739687fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_categories_name_lower', 'categories', [sa.text('lower(name)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_categories_name_lower', table_name='categories')
    # ### end Alembic commands ###
